//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer1 : DbContext
    {
        public DataModelContainer1()
            : base("name=DataModelContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sales> SalesSet { get; set; }
        public DbSet<Manager> ManagerSet { get; set; }
        public DbSet<Goods> GoodsSet { get; set; }
        public DbSet<Client> ClientSet { get; set; }
    }
}
