//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public double Cost { get; set; }
        public int ManagerId { get; set; }
        public int ClientId { get; set; }
        public int GoodsId { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Client Client { get; set; }
        public virtual Goods Goods { get; set; }
    }
}
